### ISSUE TITLE
jakarta.inject 1.0 is an explicit java module or at least reserves its automatic module name

### ISSUE THREAD

**Issue by tomdw** [eclipse-ee4j/injection-api#14]
If the community is to succeed in migrating to java modules then the basic dependencies such as javax.inject or jakarta.inject should at least reserve their automatic module name.

See http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-October/013233.html for a discussion on what that name could be. Suggested: 'java.inject'

A new release on maven central of jakarta.inject 1.0 should become available.

(also logged in https://github.com/javax-inject/javax-inject/issues/33 some time ago)

**Comment by starksm64** [comment]
A 1.0.1 release was created with an Automatic-Module-Name: jakarta.inject has been made

**Comment by tomdw** [comment]
@starksm64 sure that ‘jakarta.inject’ is correct? For version 2 as part of jakarta ee 9 yes, but for jakarta ee 8 the module name should be ‘java.inject’ i think. Also other previous javax jars have such automatic module names (e.g. java.ws.rs for the jaxrs api).

**Comment by starksm64** [comment]
Yes, you are correct.

**Comment by starksm64** [comment]
Automatic-Module-Name has been updated to java.inject
