### ISSUE TITLE
Version 1.0.1 is incompatible with OSGi

### ISSUE THREAD

**Issue by gurkerl83** [eclipse-ee4j/injection-api#15]
The release 1.0.1 is not OSGi compatible. The release candidates for version 2 are OSGi compatible.

Because the package declaration was changed in version 2, bundles of that version are incompatible with any library which rely on the javax.inject package served directly from older JDKs.

The following feature branch already exists in this repository, which seems to add the maven-bundle-plugin to generate OSGi-relevant metadata. Please provide a new version e.g., 1.0.2, with those changes applied to enable OSGi compatibility even for the version 1 library.

https://github.com/eclipse-ee4j/injection-api/tree/ee8

Thx!

**Comment by starksm64** [comment]
A 1.0.2 release has been created
