### ISSUE TITLE
jakarta.inject-api 2.0.0 seems to have mistakenly been released as patch version 1.0.2

### ISSUE THREAD

**Issue by mederel** [eclipse-ee4j/injection-api#16]
**Describe the bug**
A project I work on has an automatic dependency update mechanism, based on patch versions. According to semantic versioning, backward compatibility is maintained.

But to my surprise, using jakarta.inject-api 1.0.2 over 1.0.1 broke the compilation. It has to do with all the package renaming from javax.inject to jakarta.inject for the annotations. Of course the build is breaking.

I noticed in mvnrepository that 2 versions were released around the same time, a 2.0.0 and a 1.0.2.
Was the 1.0.2 wrongly released by containing 2.0.0 code?

**To Reproduce**
1. Have a project depending on jakarta.inject-api 1.0.1 and classes using the annotations like @Qualifier, @Singleton or @Named
2. Update the dependency to 1.0.2
3. Compile and see compilation errors because symbol not found.

**Expected behavior**
The project compiles after jakarta.inject-api patch version update

**Screenshots**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project my-project: Compilation failure: Compilation failure:
[ERROR] D:\my-project\src\main\java\package\MyClass.java:[8,19] error: package javax.inject does not exist
[ERROR] D:\my-project\src\main\java\package\MyClass.java:[19,1] error: cannot find symbol

**Comment by manovotn** [comment]
Yeah, this seems to be the case. FYI @starksm64

**Comment by starksm64** [comment]
Ok, I'll look into and fix it next week.

**Comment by tomdw** [comment]
@starksm64  Same problem here, there was also a Automatic-Module-Name fix to java.inject which should be in the 1.0.2 but is not yet available. Can someone re-release 1.0.2 correctly or create a 1.0.3 from the correct branch? Thx, would help a lot.

**Comment by starksm64** [comment]
1.0.3 has been released from the ee8 branch and released to maven central. It is visible in the jakarta staging repo and will be in maven central shortly.

https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/inject/jakarta.inject-api/1.0.3/
