### ISSUE TITLE
Add explicit module-info class file, to prevent resolving all automatic modules

### ISSUE THREAD

**Issue by VISTALL** [eclipse-ee4j/injection-api#17]
**Is your feature request related to a problem? Please describe.**
At current moment jakarta-inject library have Automatic-Module-Name attribute, if we using boot classloader it's ok.

But when multi-classloader env, resolving automatic modules have problem. Problem in this jdk code https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/module/Resolver.java#L160

For example:

 * App-Container start with self modules (which resolved by default due, java start with -p/-m arguments)
 * App-Container want initialize **app1** in own classloader, and create **ModuleLayer** for it. 
 * App-Container load all jars from **app1** and want resolve it by **Resolver**.  **But due some limitation** - not all jars must be initialized as modules (java.lang.module.Configuration#resolve  parameter *roots*, what modules must be resolved).
 * And then we try to resolve **jakarta-inject** inside **app1** which for now automatic-module. And jdk will resolve **ALL** automatic modules (https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/module/Resolver.java#L160) and it will resolve all **not targeted modules**

**Describe the solution you'd like**
Add module-info class file to jar file.  It can be placed in jar root, or in META-INF/versions/9/, old jvms skip this file anyway.

There many ways how generate it. Check gson library or log4j2. 

Also up release to 9 target.

I use own maven-plugin which generate module-info, and place it to target directory (https://github.com/consulo/java9-maven-plugin)

**Describe alternatives you've considered**
Leave as is Automatic-Module-Name

Thanks

**Comment by msgilligan** [comment]
Would there be interest in a PR to do this? If so, which of @VISTALL's suggested approaches would be preferred?

**UPDATE:** There is a PR now: https://github.com/eclipse-ee4j/injection-api/pull/19 (which bumps the target JDK 11, which may not be the most popular approach)

**Comment by rbygrave** [comment]
FYI: This issue will be resolved with https://github.com/eclipse-ee4j/injection-api/pull/20 which has been just merged.

**Comment by Ladicek** [comment]
As mentioned, fixed in #20.

**Comment by VISTALL** [comment]
Hello. New build pushed to public maven repository? If not - when it will be pushed
