### ISSUE TITLE
Backport module-info to 1.x branch

### ISSUE THREAD

**Issue by overheadhunter** [eclipse-ee4j/injection-api#23]
**Is your feature request related to a problem? Please describe.**
Now that #20 is merged, we have a proper `module-info.class` starting with version 2.0.1. Great job! 💪

However, this only targets the 2.x branch with its jakarta namespace. Many libraries still use the `javax.inject.*` package and don't want any breaking changes.

**Describe the solution you'd like**
I'd therefore propose to backport the module-info to 1.x using the module name `java.inject` and export package `javax.inject`.

**Describe alternatives you've considered**
Convince library vendors to switch to jakarta namespace. Even if successful, this would delay adoption until the next major version to avoid breaking changes.

**Additional context**
We have discussed potential compatibility issues with older Java versions in #20 and decided to use the MR-Jar approach to avoid such problems.

**Comment by Ladicek** [comment]
In my opinion, we shouldn't release anything under the `javax` namespace anymore. I'm not even sure if we're allowed to.

**Comment by overheadhunter** [comment]
> I'm not even sure if we're allowed to.

This would of course be a blocker 🙁

**Comment by starksm64** [comment]
We can't include API changes and updates to the spec under the javax namespace in Jakarta, but I don't see why we can't do service releases. There is a 1.0.4 service release that adds the module-info.class using a multi-release jar.

**Comment by overheadhunter** [comment]
The module name should be `java.inject`, though. Note the missing x (explained in #14).

**Comment by overheadhunter** [comment]
@starksm64 1.0.5 is not on Maven Central yet... not sure if you're aware of it?

**Comment by starksm64** [comment]
It was released from staging today, so it should be up soon

**Comment by rbygrave** [comment]
FYI:  It is there now: https://repo1.maven.org/maven2/jakarta/inject/jakarta.inject-api/1.0.5/

Note that it currently does not show up in the search for _search.maven.org_ yet. That is probably just a delay in the indexing for search but I also note that search.maven.org had an incident today.
