### ISSUE TITLE
So is this a fork of JSR330?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/injection-api#5]
@starksm64 I noticed, Jakarta Dependency Injection was already in Jakarta EE 8, but the package namespace remains javax.inject.

Was this a fork? I assume the Apache License allows that as long as you keep the names or the original authors there, just curious, but I trust it was where necessary also approved by Oracle and the JCP (EC).

**Comment by starksm64** [comment]
This was a fork. There should not be a need to obtain permission from Oracle.

**Comment by keilw** [comment]
Nor from the Maintenance Leads?

**Comment by keilw** [comment]
Neither of us are lawyers, but we obviously got a lot to do with this kind of stuff either in the JCP or now Jakarta EE WG. From an Apache point it seems "Derivative Work", so as the Maintenance Leads insisted, everything (in their view even the Spec which of course was non-existent anyway ;-) was covered by the Apache License, that sounds fine. It may help to put something in NOTICE.md but I'm sure your legal team at RH/IBM can confirm if it's necessary or not.

**Comment by starksm64** [comment]
The leads were contacted multiple times by both the Eclipse Foundation and Oracle without any response, so this fork was created.
